// <auto-generated />
using System;
using Examen2Poo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen2Poo.Migrations
{
    [DbContext(typeof(PlanillaDbContext))]
    partial class PlanillaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Examen2Poo.Entities.DetallePlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonificaciones");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("deducciones");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("empleado_id");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("horas_extra");

                    b.Property<decimal>("MontoHorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_horas_extra");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planilla_id");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_neto");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("detalles_planilla");
                });

            modelBuilder.Entity("Examen2Poo.Entities.EmpleadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Departamento")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("departamento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("documento");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_contratacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PuestoTrabajo")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("puesto_trabajo");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("Examen2Poo.Entities.PlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("planillas");
                });

            modelBuilder.Entity("Examen2Poo.Entities.DetallePlanillaEntity", b =>
                {
                    b.HasOne("Examen2Poo.Entities.EmpleadoEntity", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen2Poo.Entities.PlanillaEntity", "Planilla")
                        .WithMany("Detalles")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("Examen2Poo.Entities.PlanillaEntity", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
